TAXES = { ALABAMA: 4,
          ALASKA: 0,
          ARIZONA: 5.6,
          ARKANSAS: 6.5,
          CALIFORNIA: 7.25,
          COLORADO: 2.9,
          CONNECTICUT: 6.35,
          DELAWARE: 0,
          :'DIST. OF COLUMBIA'=> 6,
          FLORIDA: 6,
          GEORGIA: 4,
          HAWAII: 4,
          IDAHO: 6,
          ILLINOIS: 6.25,
          INDIANA: 7,
          IOWA: 6,
          KANSAS: 6.5,
          KENTUCKY: 6,
          LOUISIANA: 4.45,
          MAINE: 5.5,
          MARYLAND: 6,
          MASSACHUSETTS: 6.25,
          MICHIGAN: 6,
          MINNESOTA: 6.875,
          MISSISSIPPI: 7,
          MISSOURI: 4.225,
          MONTANA: 0,
          NEBRASKA: 5.5,
          NEVADA: 6.85,
          :'NEW HAMPSHIRE'=> 0,
          :'NEW JERSEY'=> 6.625,
          :'NEW MEXICO'=> 5.125,
          :'NEW YORK'=> 4,
          :'NORTH CAROLINA'=> 4.75,
          :'NORTH DAKOTA'=> 5,
          OHIO: 5.75,
          OKLAHOMA: 4.5,
          OREGON: 0,
          PENNSYLVANIA: 6,
          :'RHODE ISLAND'=> 7,
          :'SOUTH CAROLINA'=> 6,
          :'SOUTH DAKOTA'=> 4.5,
          TENNESSEE: 7,
          TEXAS: 6.25,
          UTAH: 5.95,
          VERMONT: 6,
          VIRGINIA: 5.3,
          WASHINGTON: 6.5,
          :'WEST VIRGINIA'=> 6,
          WISCONSIN: 5,
          WYOMING: 4 }
